spring:
  datasource:
    url: jdbc:postgresql:///${DB_NAME:web-public-coopac-db}?cloudSqlInstance=${CLOUD_SQL_INSTANCE:coopac-elsalvador-backend:us-central1:coopac-elsalvador-web-public-db}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&enableIamAuth=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "https://web-public-backend-prod-312882262715.us-central1.run.app/login/oauth2/code/google"
        provider:
          google:
            issuer-uri: https://accounts.google.com

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  # Configuraci贸n de sesi贸n para producci贸n con HTTPS
  session:
    timeout: 3600s
    cookie:
      name: SESSIONID
      http-only: true
      secure: true          # true en producci贸n (HTTPS)
      same-site: none       # none permite cookies entre dominios (frontend y backend separados)
      path: /
      domain: .us-central1.run.app  # Permite cookies en subdominios de Cloud Run

app:
  frontend:
    url: https://coopacelsalvador.com

cors:
  allowed:
    origins:
      - https://coopacelsalvador.com
      - https://www.coopacelsalvador.com

file:
  storage:
    type: ${STORAGE_TYPE:gcs}
    gcs:
      bucket-name: ${GCS_BUCKET_NAME}
      project-id: ${GCP_PROJECT_ID}

logging:
  level:
    com.elsalvador.coopac: INFO
    org.springframework: INFO
