spring:
  datasource:
    url: jdbc:postgresql:///${DB_NAME:web-public-coopac-db}?cloudSqlInstance=${CLOUD_SQL_INSTANCE:coopac-elsalvador-backend:us-central1:coopac-elsalvador-web-public-db}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&enableIamAuth=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "https://api-web.coopacelsalvador.com/login/oauth2/code/google"
        provider:
          google:
            issuer-uri: https://accounts.google.com

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  # Configuración de sesión para subdominios compartidos
  session:
    store-type: none
    timeout: 3600s
    cookie:
      name: JSESSIONID
      http-only: true
      secure: true          # Obligatorio con SameSite=None
      same-site: none       # Necesario para cross-site (subdominios diferentes)
      path: /
      domain: .coopacelsalvador.com  # Compartir cookies entre subdominios

server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
        domain: .coopacelsalvador.com

app:
  frontend:
    url: https://coopacelsalvador.com

cors:
  allowed:
    origins:
      - https://coopacelsalvador.com
      - https://www.coopacelsalvador.com
      - https://api-web.coopacelsalvador.com

file:
  storage:
    type: ${STORAGE_TYPE:gcs}
    gcs:
      bucket-name: ${GCS_BUCKET_NAME}
      project-id: ${GCP_PROJECT_ID}

logging:
  level:
    com.elsalvador.coopac: INFO
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
