spring:
  datasource:
    url: jdbc:postgresql:///${DB_NAME:web-public-coopac-db}?cloudSqlInstance=${CLOUD_SQL_INSTANCE:coopac-elsalvador-backend:us-central1:coopac-elsalvador-web-public-db}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&enableIamAuth=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://coopacelsalvador.com/login/oauth2/code/google"

app:
  frontend:
    url: https://coopacelsalvador.com

cors:
  allowed:
    origins:
      - https://coopacelsalvador.com
      - https://www.coopacelsalvador.com

file:
  storage:
    type: ${STORAGE_TYPE:gcs}
    gcs:
      bucket-name: ${GCS_BUCKET_NAME}
      project-id: ${GCP_PROJECT_ID}

logging:
  level:
    com.elsalvador.coopac: INFO
    org.springframework: INFO
