spring:
  application:
    name: cac-elsalvador-backend

  # Configuración de seguridad OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
        provider:
          google:
            issuer-uri: https://accounts.google.com

  datasource:
    url: jdbc:postgresql://localhost:5432/cac-elsalvador-web
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1jerete1}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: never

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

    # Configuración de sesión para desarrollo con SPA en puerto diferente
    session:
      timeout: 3600s
      cookie:
        name: SESSIONID
        http-only: true
        secure: false         # false en desarrollo (localhost HTTP)
        same-site: none       # None permite cookies entre localhost:8080 y localhost:4200
        path: /

  jackson:
    time-zone: America/Lima

server:
  port: ${PORT:8080}
  shutdown: graceful
  forward-headers-strategy: framework
  compression:
    enabled: true

# Configuración de aplicación
app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}

cors:
  allowed:
    origins:
      - http://localhost:4200
      - https://coopacelsalvador.com

file:
  storage:
    type: local
    local:
      base-path: ${FILE_STORAGE_PATH:./uploads}
    gcs:
      bucket-name: ${GCS_BUCKET_NAME}
      project-id: ${GCP_PROJECT_ID}
