spring:
  datasource:
    url: jdbc:postgresql://34.9.66.96:5432/web-public-coopac-db?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 20000
      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: America/Lima
    open-in-view: false

server:
  port: ${PORT:8080}
  shutdown: graceful

cors:
  allowed:
    origins:
      - https://coopac-el-salvador-fronted.web.app
      - https://coopac-el-salvador-fronted.firebaseapp.com
      - https://coopacelsalvador.com

file:
  storage:
    type: gcs
    gcs:
      bucket-name: ${GCS_BUCKET_NAME}
      project-id: ${GCS_PROJECT_ID:coopac-elsalvador-backend}
      base-url: https://storage.googleapis.com

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  level:
    root: INFO
    com.elsalvador.coopac: INFO
