spring:
  application:
    name: cac-elsalvador-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/cac-elsalvador-web
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1jerete1}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: never

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  jackson:
    time-zone: America/Lima

server:
  port: ${PORT:8080}
  shutdown: graceful
  forward-headers-strategy: framework
  compression:
    enabled: true

cors:
  allowed:
    origins:
      - http://localhost:4200
      - http://localhost:3000

file:
  storage:
    type: local
    local:
      base-path: ./uploads
      base-url: http://localhost:8080/uploads
